#! /bin/bash

vpp_ws_dir=$1

if [ -z "${vpp_ws_dir}" ]; then
    echo "Usage: $0 <vpp-ws-dir>" >&2
    exit 1
fi

# Clean our local packages, since cargo doesn't detect the addition of the instrument coverage flag as needing to rebuild already-built packages
cargo clean -p vpp-plugin -p vpp-example-plugin -p vpp-test-plugin -p vpp-plugin-api-gen -p vpp-plugin-macros
# Remove old coverage information, since grcov won't overwrite it
rm -r target/coverage

export RUSTFLAGS=-Cinstrument-coverage

cargo test --workspace

$(dirname "$0")/run "${vpp_ws_dir}"

grcov . /tmp/vpp-unittest-IntegrationTestCase/ /tmp/vpp-unittest-ExampleTestCase/ --binary-path target/debug -s . --ignore-not-existing --ignore 'target/*' --ignore '/*' -t html -o target/coverage
rm *.profraw */*.profraw /tmp/vpp-unittest-IntegrationTestCase/*.profraw /tmp/vpp-unittest-ExampleTestCase/*.profraw
